import React from 'react';

const movies = [
  { id: "1", name: "12 years a Slave" },
  { id: "2", name: "28 Weeks later" },
  { id: "3", name: "Akira" },
  { id: "4", name: "Alien, Predator, Aliens vs Predator" },
  { id: "5", name: "American Pie 2" },
  { id: "6", name: "American Pie: The Wedding" },
  { id: "7", name: "Animal House" },
  { id: "8", name: "Ant-Man" },
  { id: "9", name: "Apocalypse Now" },
  { id: "10", name: "Argo" },
  { id: "11", name: "Avengers" },
  { id: "12", name: "Avengers: Age of Ultron" },
  { id: "13", name: "Baby Driver" },
  { id: "14", name: "Babylon 5: Collection" },
  { id: "15", name: "Back to the Future" },
  { id: "16", name: "Batman: Collection" },
  { id: "17", name: "Battle Royale: Limited edition" },
  { id: "18", name: "Battlestar Galactica: movies" },
  { id: "19", name: "Battlestar Galactica: Season 1" },
  { id: "20", name: "Battlestar Galactica: Season 2" },
  { id: "21", name: "Big Hero 6" },
  { id: "22", name: "Black Mass" },
  { id: "23", name: "Blade 2" },
  { id: "24", name: "Blade Runner: Final cut" },
  { id: "25", name: "Blue Planet: Collection" },
  { id: "26", name: "Bolt" },
  { id: "27", name: "Bond: Collection" },
  { id: "28", name: "Borat" },
  { id: "29", name: "Bourne: Collection" },
  { id: "30", name: "Bunraku" },
  { id: "31", name: "Can't Hardly Wait" },
  { id: "32", name: "Captain America" },
  { id: "33", name: "Captain America: Civil War" },
  { id: "34", name: "Casablanca" },
  { id: "35", name: "Code Geass: R2" },
  { id: "36", name: "Commando" },
  { id: "37", name: "Corpse Bride" },
  { id: "38", name: "Cowboy Bebop" },
  { id: "39", name: "Cruel Intentions" },
  { id: "40", name: "Deadpool" },
  { id: "41", name: "Despicable Me" },
  { id: "42", name: "Despicable Me 2" },
  { id: "43", name: "Despicable Me 3" },
  { id: "44", name: "Die Hard" },
  { id: "45", name: "Die Hard 2" },
  { id: "46", name: "Dredd" },
  { id: "47", name: "Enter the Dragon" },
  { id: "48", name: "Fast & Furious 6" },
  { id: "49", name: "Fast & Furious 7" },
  { id: "50", name: "Fast & Furious 8" },
  { id: "51", name: "Fast & Furious: 1-5 collection" },
  { id: "52", name: "Fifth Element" },
  { id: "53", name: "Final Fantasy VII: Advent Children Complete" },
  { id: "54", name: "Final Fantasy XV: Kingsglaive" },
  { id: "55", name: "Firefly" },
  { id: "56", name: "Frozen" },
  { id: "57", name: "Full Metal Panic: Collection" },
  { id: "58", name: "G.I. Joe: Collection" },
  { id: "59", name: "Game of Thrones: Season 1" },
  { id: "60", name: "Game of Thrones: Season 2" },
  { id: "61", name: "Game of Thrones: Season 3" },
  { id: "62", name: "Game of Thrones: Season 4" },
  { id: "63", name: "Game of Thrones: Season 5" },
  { id: "64", name: "Game of Thrones: Season 6" },
  { id: "65", name: "Ghost in the Shell" },
  { id: "66", name: "Godzilla (2016)" },
  { id: "67", name: "Grand Budapest Hotel" },
  { id: "68", name: "Gremlins" },
  { id: "69", name: "Gremlins 2" },
  { id: "70", name: "Guardians of the Galaxy" },
  { id: "71", name: "Guardians of the Galaxy 2" },
  { id: "72", name: "Hangover" },
  { id: "73", name: "Hangover 2" },
  { id: "74", name: "Hannibal" },
  { id: "75", name: "Hobbit: An unexpected Journey" },
  { id: "76", name: "Hobbit: Battle of the Five Armies" },
  { id: "77", name: "Hobbit: Desolation of Smaug" },
  { id: "78", name: "How to train your Dragon" },
  { id: "79", name: "How to train your Dragon 2" },
  { id: "80", name: "Hugo" },
  { id: "81", name: "Independence Day" },
  { id: "82", name: "Indiana Jones: Collection" },
  { id: "83", name: "Inside Out" },
  { id: "84", name: "Iron Man 3" },
  { id: "85", name: "Iron Man: 1-2" },
  { id: "86", name: "Iron Sky" },
  { id: "87", name: "Jurassic Park: Trilogy" },
  { id: "88", name: "Jurassic World" },
  { id: "89", name: "Kiki's Delivery service" },
  { id: "90", name: "Kingsman" },
  { id: "91", name: "Kung-Fu Panda" },
  { id: "92", name: "Kung-Fu Panda 2" },
  { id: "93", name: "Kung-Fu Panda 3" },
  { id: "94", name: "Laputa Castle in the Sky" },
  { id: "95", name: "Lawrence of Arabia" },
  { id: "96", name: "Lethal Weapon: Collection" },
  { id: "97", name: "Life" },
  { id: "98", name: "Little Shop of Horrors" },
  { id: "99", name: "Lord of The Rings: Trilogy" },
  { id: "100", name: "Machete" },
  { id: "101", name: "Machete Kills" },
  { id: "102", name: "Mad Max: Collection" },
  { id: "103", name: "Mad Max: Fury Road" },
  { id: "104", name: "Men in Black 3" },
  { id: "105", name: "Minions" },
  { id: "106", name: "Mission Impossible: Ghost Protocol" },
  { id: "107", name: "Mission Impossible: Trilogy" },
  { id: "108", name: "Moana/Vaiana" },
  { id: "109", name: "Monsters inc: University" },
  { id: "110", name: "Mummy (2017)" },
  { id: "111", name: "My Neighbour Totoro" },
  { id: "112", name: "Napapiirin sankarit 2" },
  { id: "113", name: "Napapiirin sankarit 3" },
  { id: "114", name: "Nausicaä of the Valley of the Wind" },
  { id: "115", name: "Nightmare Before Christmas" },
  { id: "116", name: "Ninja Scroll" },
  { id: "117", name: "Ocean's: Trilogy" },
  { id: "118", name: "Outlaw Star" },
  { id: "119", name: "Pacific Rim" },
  { id: "120", name: "Penguins of Madagascar" },
  { id: "121", name: "Pirates of the Caribbean: At World's End" },
  { id: "122", name: "Pirates of the Caribbean: Curse of the Black Pearl"},
  { id: "123", name: "Pirates of the Caribbean: Dead Man's Chest" },
  { id: "124", name: "Pirates of the Caribbean: On stranger tides" },
  { id: "125", name: "Pirates of the Caribbean: Salazar's Revenge" },
  { id: "126", name: "Planet Earth" },
  { id: "127", name: "Planet Earth 2" },
  { id: "128", name: "Planet of the Apes: Classic collection" },
  { id: "129", name: "Pride and Prejudice: Series" },
  { id: "130", name: "Princess Bride" },
  { id: "131", name: "Princess Mononoke" },
  { id: "132", name: "Prometheus" },
  { id: "133", name: "Rare Exports" },
  { id: "134", name: "Ratatouille" },
  { id: "135", name: "Rock of Ages" },
  { id: "136", name: "Samurai Champloo" },
  { id: "137", name: "Serenity" },
  { id: "138", name: "Shawshank Redemption" },
  { id: "139", name: "Sherlock Holmes" },
  { id: "140", name: "Sherlock Holmes: A Game of Shadows" },
  { id: "141", name: "Silence of the Lambs" },
  { id: "142", name: "Silent Movie" },
  { id: "143", name: "Skyfall" },
  { id: "144", name: "Snowpiercer" },
  { id: "145", name: "Spectre" },
  { id: "146", name: "Spiderman: Homecoming" },
  { id: "147", name: "Spirited Away" },
  { id: "148", name: "Star Trek: Beyond" },
  { id: "149", name: "Star Trek: Into Darkness" },
  { id: "150", name: "Star Wars: Collection" },
  { id: "151", name: "Star Wars: Rogue One" },
  { id: "152", name: "Star Wars: The Force Awakens" },
  { id: "153", name: "Stardust" },
  { id: "154", name: "Stargate" },
  { id: "155", name: "Star-Trek (2009)" },
  { id: "156", name: "Steven Seagal Collection" },
  { id: "157", name: "Tangled" },
  { id: "158", name: "Tarantino: Collection" },
  { id: "159", name: "Terminator: Quadrilogy" },
  { id: "160", name: "The Black Tower" },
  { id: "161", name: "The Castle of Cagliostro" },
  { id: "162", name: "The Chronicles of Riddick" },
  { id: "163", name: "The Dark Knight" },
  { id: "164", name: "The Dark Knight Rises" },
  { id: "165", name: "The Departed" },
  { id: "166", name: "The Dictator" },
  { id: "167", name: "The Expendables" },
  { id: "168", name: "The Expendables 2" },
  { id: "169", name: "The Expendables 3" },
  { id: "170", name: "The Great Wall" },
  { id: "171", name: "The Handmaid" },
  { id: "172", name: "The Hateful Eight" },
  { id: "173", name: "The Hitman's Bodyguard" },
  { id: "174", name: "The Holiday" },
  { id: "175", name: "The Incredible Hulk" },
  { id: "176", name: "The Interview" },
  { id: "177", name: "The Matrix" },
  { id: "178", name: "The Raid 2" },
  { id: "179", name: "The Raid: Redemption" },
  { id: "180", name: "The Rock" },
  { id: "181", name: "The Wire: Collection" },
  { id: "182", name: "The Wizard of Oz" },
  { id: "183", name: "The Wolverine" },
  { id: "184", name: "Thor" },
  { id: "185", name: "Thor: Ragnarök" },
  { id: "186", name: "Thor: The Dark World" },
  { id: "187", name: "Top Gun" },
  { id: "188", name: "Train to Busan" },
  { id: "189", name: "Transformers" },
  { id: "190", name: "Transformers: The Last Knight" },
  { id: "191", name: "Transporter" },
  { id: "192", name: "Up" },
  { id: "193", name: "Valerian" },
  { id: "194", name: "Wall-E" },
  { id: "195", name: "Warcraft" },
  { id: "196", name: "Weird Science" },
  { id: "197", name: "Wonder Woman" },
  { id: "198", name: "Wreck-it Ralph" },
  { id: "199", name: "X-Men: Apocalypse" },
  { id: "200", name: "X-Men: Days of Future Past Rogue-Cut" },
  { id: "201", name: "Your Highness" },
  { id: "202", name: "Your Name" },
  { id: "203", name: "Zootropolis" },
  { id: "204", name: "Infernal Affairs Trilog" }
]

export default movies;